### ISSUE TITLE
The reports do not take into account the new exchange rate changes.

### ISSUE THREAD

**Issue by BaxAndrei** [crater-invoice/crater#616]
**Describe the bug**
Although it is displayed correctly in the dashboard, when reports are generated, the amounts are not converted according to the rate. The values are just set without being converted and the main currency is added to the queue.
If, for example, I have the main currency RON (1 EURO = 5 RON) and an invoice of 2 EURO, the report will show 2 RON.

**Expected behavior**
Convert everything to the main currency just like on the dashboard. Instead of 2 RON to be 10 RON (5 * 2).

**Screenshots**
![image](https://user-images.githubusercontent.com/12484505/144508719-2ad40e49-7313-483c-8569-2e43c6db1816.png)
![image](https://user-images.githubusercontent.com/12484505/144508770-159938ad-e8ea-4a1f-97f4-556f7ca8c1bb.png)

**Please complete the following information:**
- Crater version: 5.0.2
- PHP version: 7.4.26 
- Database type and version: 5.7.34 - MySQL Community Server (GPL)

**Optional info**
- OS:  Windows 11 21H1
- Browser: Google Chrome | 96.0.4664.45 (Official Build) (64-bit)

**Comment by mohitpanjwani** [comment]
Fixed on [5.0.4](https://github.com/crater-invoice/crater/releases/tag/5.0.4)

**Comment by BaxAndrei** [comment]
> Fixed on [5.0.4](https://github.com/crater-invoice/crater/releases/tag/5.0.4)

I see this issue still occur there: https://URL/admin/customers/13/view https://prnt.sc/22lgugp
