### ISSUE TITLE
Can't load css after updating to 5.0.3

### ISSUE THREAD

**Issue by Vikingoa** [crater-invoice/crater#620]
**Describe the bug**
The file /build/assets/main.5b54a72b.css is not loaded. 
Console error : The stylesheet was not loaded because its MIME type, "text/html" is not "text/css.

Thus the website doesn't have any css styling and is unusable.
On another instance of crater that I have the update didn't cause any problems (same server).

The backup of my sqlite database doesn't work so I'm a little bit stuck here.

**Expected behavior**
Expected to have the page displaying properly.

**Please complete the following information:**
- Crater version: 5.0.3
- PHP version: 7.4
- Database type and version: sqlite

**Optional info**
Tested on multiple browsers / OS.

**Comment by Vikingoa** [comment]
Update : Everything that is in /build is not working (js etc).
Is there a way to fix this / to backup my data to start on a new crater installation ?

**Comment by dwyer125** [comment]
I think this is my same issue. Went from 5.0.1 to 5.0.3 and the webpage loads without styling and is unusable.

**Comment by mohitpanjwani** [comment]
Hey @Vikingoa @dwyer125 

We are looking into what caused this issue as it should be working without any manual changes.

 Meanwhile if you guys are stuck, please run: yarn install and yarn build to compile new build files. 

That should fix the issues.  Let me know if there’s anything else.

**Comment by mohitpanjwani** [comment]
Hey guys, we've just fixed this. 

It was an issue when going from 5.0.1 to 5.0.3. 

This can easily be fixed if you do what I suggested above but If you're still stuck and cannot update from UI or run above commands, please change your version manually to 5.0.1 & then run following command to update: 
`php artisan crater:update`.

**Comment by indygill** [comment]
I'm still having issues after upgrading. A lot of the files inside /build/assets path are returning 404 errors. The request urls don't include the word "build" however. 

Everything does seem to be working fine now except for this. Here's a list of 404 errors when navigating to /admin/dashboard

`main.08c278b7.js:1 GET /assets/Dashboard.ae2f662d.js net::ERR_ABORTED 404
main.08c278b7.js:1 GET /assets/vendor.9f353b75.js net::ERR_ABORTED 404
main.08c278b7.js:1 GET /assets/LineChart.6319ca8d.js net::ERR_ABORTED 404
main.08c278b7.js:1 GET /assets/InvoiceIndexDropdown.990a9432.js net::ERR_ABORTED 404
main.08c278b7.js:1 GET /assets/EstimateIndexDropdown.c130daf0.js net::ERR_ABORTED 404
main.08c278b7.js:1 GET /assets/BaseTable.560b35cb.js net::ERR_ABORTED 404
main.4579ecfd.css:1 GET /fonts/Poppins-Semibold.ttf net::ERR_ABORTED 404
vendor.9f353b75.js:5 TypeError: Cannot read properties of null (reading 'currency')
    at Dashboard.ae2f662d.js:1
    at b (vendor.9f353b75.js:2)
    at mZ (vendor.9f353b75.js:2)
    at BaseTable.560b35cb.js:1
    at Kgx (vendor.9f353b75.js:2)
    at BaseTable.560b35cb.js:1
    at Kgx (vendor.9f353b75.js:2)
    at Proxy.<anonymous> (BaseTable.560b35cb.js:1)
    at aZ (vendor.9f353b75.js:2)
    at FJ.zo [as fn] (vendor.9f353b75.js:2)
main.08c278b7.js:1 GET /assets/BaseMultiselect.96cc3557.js net::ERR_ABORTED 404`

I can confirm the files do exist in the /public/build directory.

**Comment by Vikingoa** [comment]
> Hey guys, we've just fixed this.
> 
> It was an issue when going from 5.0.1 to 5.0.3.
> 
> This can easily be fixed if you do what I suggested above but If you're still stuck and cannot update from UI or run above commands, please change your version manually to 5.0.1 from `settings` table & then run following command to update: `php artisan crater:update`.

Worked for me, thanks !
