### ISSUE TITLE
Payments that are unattached to Invoice

### ISSUE THREAD

**Issue by kostaj** [crater-invoice/crater#635]
**Is your feature request related to a problem? Please describe.**
1. I am able to create a Payment for a Client that is not attached to an Invoice. I am not sure if this is intended.
2. This Income shows up in Customers > Client as Net Income in the graph and on the right suggesting it is.
3. However, it does not show up in the Profit & Loss report (if no Sales for that client, Income = 0).
2. If I try to update that invoice I get Error: Server Error. This can be fixed by attaching it to an invoice.

I suspect either it should be enforced that all Payments are attached to an Invoice *OR*  this is an intended behaviour but Payments without Invoices are not properly handled and this is a bug.

**Describe the solution you'd like**

I would like to be able to create a Payment for a Client that is not attached to an invoice in order to keep a running total of Income from that client.  The issue with marking the other invoices as paid is another issue.

There is value in adding Income that is not attached to an Invoice for bookkeeping. E.g. as a retainer, advance, or payment that spans multiple invoices.

If you are curious why I'd do this, I use this type of software to shadow bill my income rather than actually send out invoices to clients.   Unfortunately due to some probably intentional healthcare industry insanity outside my control, I get paid as a lump sum several weeks later without the ability to tie it back to a specific day, service etc. So don't notice if I've been short changed unless I do something like this to keep track of my submitted billings.

I know this is an edge case but I suspect the bug as described above affects more people.  Previously I just did this with an SQL script that chronologically marks invoices paid and calculates the sums as the balance received exceeds their sum sales in invoiceninja. Thanks!

**Please complete the following information:**

Crater version: 5.0.4
PHP version: 7.4.25
Database type and version: mariadb 10.5.12

**Comment by dwyer125** [comment]
I also record payments where there was no invoice sent. So I would like that functionality to continue. 
So please just add the income to the profit and loss report. 
Maybe it could be added to the sales report under each customer as a separate line for non-invoiced income?

**Comment by mohitpanjwani** [comment]
This is fixed on https://github.com/crater-invoice/crater/releases/tag/5.0.5

Previously we were not considering the payments without invoice on the profit and loss report. 

Regarding the issue with updating payment, we made some changes to that too. Can you test that again and see if its working properly now? 

Closing the issue but please feel to reopen it if it’s still not working for you.

**Comment by kostaj** [comment]
Thanks @mohitpanjwani ! That was very quick. It now shows up in Profits and Loss reporting. I am not sure I can re-open an issue you have closed, but there is still a problem with changing the the value of a payment without an invoice.

Here is an arbitrary test payment:
![image](https://user-images.githubusercontent.com/33677112/145491887-5955c99f-d8fd-4004-a0f6-8a6f35172661.png)

If I try to edit the amount I get this error in the top right:
![image](https://user-images.githubusercontent.com/33677112/145491930-f60e3112-80e8-48ad-9a4a-9efc449c569a.png)

From ./storage/logs/laravel*.log after clicking Update Payment:

```
[2021-12-09 17:33:29] production.ERROR: Call to a member function addInvoicePayment() on null {"userId":1,"exception":"[object] (Error(code: 0): Call to a member function addInvoicePayment() on null at /home/www/craterapp/crater/app/Models/Payment.php:200)
(...)

```
Nothing in the nginx error log. From the access log:

`X.X.X.X - - [09/Dec/2021:17:31:38 -0600] "PUT /api/v1/payments/7 HTTP/1.1" 500 44 "https://DOMAIN.TLD/admin/payments/7/edit" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0" "-"`
