### ISSUE TITLE
Database should be empty

### ISSUE THREAD

**Issue by sashi** [crater-invoice/crater#698]
**Describe the bug**
Error "database should be empty" in installation wizard
**Expected behavior**
Continue the installation 

Using docker. 
Git checkout the branch. Edit the .env file.
Got everything configured and put the docker container up

I was able to get crater working on a different machine. Not sure why it isn't working on this one

**Comment by mohitpanjwani** [comment]
Hi @sashi, 

You're getting this error because you updated the `.env` file I think. 

Can you replace your `.env` file with `.env.example` and try again? I think that should fix it.

**Comment by melaniecarr23** [comment]
I'm having the same problem.  Replaced the .env file with the example.  When I try dropping the crater db (which is empty), I get an error that it doesn't exist, and when I create it I get the database should be empty error.  Testing on my local machine.

**Comment by sashi** [comment]
Hi @mohitpanjwani 
Unfortunately that did not work. Still shows as database should be empty

**Comment by melaniecarr23** [comment]
When you view the database, it has tables in it, right?  I created a separate issue because I was getting more than just that error from that page of the install.  I get 9 tables inserted into the database from that page, but sometimes I get an internet connectivity issue (I'm on a local machine, so there isn't one).

**Comment by melaniecarr23** [comment]
@sashi 

The following worked for me:
- drop all the tables in the crater db
- follow my solution in the link below:

https://github.com/crater-invoice/crater/issues/700

It looks like the installation stops when migrating the password_resets table, so I made a change to that and it worked.
